### ISSUE TITLE
cadCAD website update to include cadCAD_Edu MOOC

### ISSUE THREAD

**Issue by Jeff-Emmett** [cadCAD-org/cadCAD#215]
## 📋   Anything to add?
Add a prominent link to the cadCAD Edu course (cadcad.education) to the landing page of cadCAD.org

## 🎉   Subtasks

- [ ] Identify asset owner (Jeff can help with this)
- [ ] Decide where link/button need to go
- [ ] Publish site change

## 🤼‍♂️   Reviewer

@Jeff-Emmett
