### ISSUE TITLE
Update cadCAD website [Infra/Admin] [Urgency: Med] [Importance: High]

### ISSUE THREAD

**Issue by seichris** [cadCAD-org/cadCAD#222]
## 📋 Anything to add?

Handoff website assets to cadCAD community, ...

## 🎉 Subtasks

- [ ] Publicize who was website write access, in website readme repo (?!)
- [ ] Hand over access to the website (?!)
- [ ] Write content for the website in gDoc (link)
- [ ] Make design in Figma (link)
- [ ] ...

## 🤼‍♂️ Reviewer, Reported By

@Sergei @Jeff-Emmett 

## 🔗 Work doc - inspirational links

--

## 🔧 Status

--

## 👷 Skills

--
